### ISSUE TITLE
issue in login 

### ISSUE THREAD

**Issue by ciphereck** [devgrpnitkkr/Techspardha19-App#24]
2019-09-16 22:59:07.313 11600-11670/? E/cezp: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at cezo.<init>(:com.google.android.gms@19056038@19.0.56 (100406-262933554):1)
        at cezp.<init>(:com.google.android.gms@19056038@19.0.56 (100406-262933554):2)
        at cers.b(:com.google.android.gms@19056038@19.0.56 (100406-262933554):16)
        at saz.a(:com.google.android.gms@19056038@19.0.56 (100406-262933554):36)
        at saz.a(:com.google.android.gms@19056038@19.0.56 (100406-262933554):92)
        at aqwi.call(Unknown Source:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at sif.b(:com.google.android.gms@19056038@19.0.56 (100406-262933554):33)
        at sif.run(:com.google.android.gms@19056038@19.0.56 (100406-262933554):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sny.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-09-16 22:59:08.318 11981-11981/? E/oadcastreceive: Not starting debugger since process cannot load the jdwp agent.
2019-09-16 22:59:08.334 11981-11981/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
2019-09-16 22:59:14.043 1253-1357/? E/MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
2019-09-16 22:59:24.248 1253-1357/? E/MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
2019-09-16 22:59:34.575 1253-1357/? E/MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
2019-09-16 22:59:43.425 1253-1290/? E/libc: Access denied finding property "vendor.debug.sf.stc_interval"
2019-09-16 22:59:43.425 1253-1290/? E/libc: Access denied finding property "vendor.debug.bq.dump"

**Comment by Asgardian8740** [comment]
Kindly pull the updated  repo.

**Comment by smsibtainrn** [comment]
Basically this is a permission issue and some of the cell phones don't give the correct/actual logs. You have missed any permission which has to be mention in your AndroidManifest.xml file.

**Comment by sathishsubramani-2103** [comment]
If you are using any native library please update that and then run. The same issue does not come in older android versions if you using a new android version it may through this error. Thanks
